# Generated by Django 4.1 on 2022-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha1', models.CharField(max_length=250)),
                ('text1', models.TextField()),
            ],
        ),
    ]
